FROM golang:alpine as builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o compiledClient -v -ldflags="-w -s" ./client/

FROM busybox

WORKDIR /app

COPY --from=builder /app/compiledClient /usr/bin/

ENTRYPOINT ["compiledClient"]
